### PR TITLE
Fix #1

### LINKED ISSUE #1: Update the HMDB test for outdated identifiers
Which currently fails because of the new HMDB identifier scheme.

See https://github.com/BiGCAT-UM/WikiPathwaysCurator/commit/249e873f24cf82164c594136c9d818bfd5333926

### PR DESCRIPTION
**Pull request by DeniseSl22**
Added file with sec,primary IDs from HMDB, added test for WPs Jenkins.
Now the request should point to the correct base :)

### CODE REVIEW

File: src/test/java/nl/unimaas/bigcat/wikipathways/curator/HMDBSecMetabolites.java [hunk 1]
```diff
@@ -0,0 +1,67 @@
++/* Copyright (C) 2018  Egon Willighagen <egon.willighagen@gmail.com>
```
Comment (egonw) [inline src/test/java/nl/unimaas/bigcat/wikipathways/curator/HMDBSecMetabolites.java:1]: Please add a second line here which adds you as copyright owner too. Check this example: https://github.com/cdk/cdk/blob/master/storage/io/src/main/java/org/openscience/cdk/io/GhemicalMMReader.java

**Review by egonw — CHANGES_REQUESTED** [review]
Otherwise looks fine.

**Review by egonw — COMMENTED** [review]
OK, looks good now.
